#!/bin/bash
apt -y update
apt -y install nginx

myip=`curl http://169.254.169.254/latest/meta-data/public-ipv4`
cat <<EOF > /var/www/html/index.html
<html>
<h2>Build by ATV </h2><br>
<p>
Server IP: $myip<br>
</html>
EOF

systemctl enable nginx
systemctl start nginx
